### ISSUE TITLE
Non-timeouts retrieval

### ISSUE THREAD

**Issue by pmangg** [alexmanalex/nba_timeouts#1]
I'm wondering if you'd get more representative treatment value of 0, if you endow some ball domain knowledge when retrieving the non-timeouts:

1. [When timeouts happen (from Quora)](https://www.quora.com/Who-has-the-right-to-ask-for-a-timeout-in-the-NBA). Reproduced here:

- Live ball - when the team has possession of the ball and the clock is running, only players on the court may call a timeout. The most common version of this you will see is after the opponent makes a small run (6–10 points in a row), the point guard will typically run the ball past half court towards the referee then call for timeout for the purpose of slowing the opposing momentum and figuring out a way to stop the opponent from scoring.

- Free throw - when your team is at the free throw line, both players and coaches can call for a timeout to take place before the last free throw. Teams don’t often do this as they don’t usually get possession of the ball after the free throw; it’s either if it’s a close game and they need the person shooting to miss, or they want to set up a defensive play.

- Dead ball - when the ball is not in play, the clock has stopped, and the opponent does not have possession of the ball, both players and coaches may call timeout. There can be many reasons why this timeout would be called, but the most common one is the coach calling timeout after the opposing team scores a run, and the coach is frustrated with their team.

- Media timeout - when both teams get rest and strategy time for the purpose of showing advertisements for TV stations. These can be either good or bad for your team, depending on if you have momentum or not. Typically, there is 1 per quarter.

2. IIRC, there's often a sequence of timeouts called very close to each other when the scores are tied, and very near to the end of the game (often ending up in a buzzer beater).

@alexmanalex is there a way to incorporate the above info? One naive way is to try to make sure that the distribution of timeout types (type could "Live ball", "Free throw", etc) are approximately the same for both non-timeouts and timeouts (i.e., we'd stratify sample instead of uniformly at random sample).

**Comment by alexmanalex** [comment]
1. I agree these non timeout pauses in the game offer useful information and they wouldn't be hard to retrieve. 
One known, related shortcoming of the analysis as posted, is that we should be using the 'average treatment of the treated', not the 'average treatment effect' since we care about the causal effect of timeouts at the times when timeouts are taken.  

2. I am not using the timeouts from end of game in the analysis. I think of these timeouts as being used for different reasons than at other times. Also, the measure of timeout value I am using is the 3 minutes scoring differential after timeout. So in the last 3 minutes, some extra steps would need to be taken to get that measure.

**Comment by pmangg** [comment]
> the 'average treatment of the treated', not the 'average treatment effect' since we care about the causal effect of timeouts at the times when timeouts are taken.

Right, so this would be `E[causal effect of timeout | timeouts were taken]` instead of `E[causal effect of timeout]`?

> I am not using the timeouts from end of game in the analysis. I think of these timeouts as being used for different reasons than at other times.

Gotcha 👍

**Comment by alexmanalex** [comment]
Returning to this, I definitely want to include your initial suggestion in part (1). I really like the idea of stratifying the sampling of non-timeouts so that the distribution of timeout types are similar between treated and untreated. 

This is really cool. So, by doing this we're implying that "event type" is a confounder which holds water.  This stratified sampling does the job of controlling for "event type".

**Comment by alexmanalex** [comment]
You know what, I think that all the confounders in DAG could be controlled for by stratified sampling like this.

**Comment by alexmanalex** [comment]
Ok, I realized that sampling to retrieve non-timeouts is not necessary at all in my original solution. We can treat all events that are not timeouts as non-timeout events. This dataset is unique in that it is so huge, many event are captured. I think this threw me off originally in defining a placebo event. All events that are not timeouts are the placebo events in this observational (non-RCT) dataset.  

I think that the two solutions for causal inference here are:

1. Retrieve the stratified sample, stratified according to the joint distribution of all the confounding variables on timeouts as the "non-timeout" event. We would achieve "conditional exchangeability" here. 

2. Use *all* events that are not timeouts as placebo (i.e. no uniform sampling as I am doing now) and use stratification/IPW to achieve conditional exchangeability (including "event type" as another confounder). We get to use all the data and let the g-method (IPW/Standardization) do the work of achieving conditional exchangeability. 


So... I think that (2) is superior here. In (1), if a "level of stratification" is rare in all non-timeout events, relative to the timeout events, then we can end up with a small stratified sample. I think we will always end up with a variance in part (2) that is less than or equal to variance in part (1) for our estimator, `$E[Y^{a=0}]$`. 

Should look into this.

**Comment by pmangg** [comment]
Closing this -- just cleaning up my github.
